#!/usr/bin/env bash

DEFAULT_DIR="." # use current directory by default
DIR=${1:-$DEFAULT_DIR}
DIR="$(realpath $DIR)"
PLUGIN_NAME="$(basename $DIR)"
TMP_DIR="/tmp/wp-plugin/$PLUGIN_NAME"
DEST_DIR=".wp-build"

clear >$(tty)

mkdir -p "$(dirname $TMP_DIR)"
rm -rf $TMP_DIR
echo "Copying plugin files to $TMP_DIR..."
cp -R $DIR $TMP_DIR
cd $TMP_DIR

# call composer install
if [ -f 'composer.json' ]; then
	echo "Installing composer dependencies..."
	composer install --no-dev
fi

# call npm install
if [ -f 'composer.json' ]; then
	echo "Installing NPM dependencies..."
	npm install
fi

echo "Erasing development files..."

# erase some dev files
rm -rf ./.git
rm -rf ./.editorconfig
rm -rf ./.gitignore
rm -rf ./node_modules
rm -rf ./package-lock.json
rm -rf ./composer.lock
rm -rf ./release
rm -rf "./$DEST_DIR"

# build the zip file
echo "Creating zip file..."
mkdir "$DIR/build"
rm -rf "$DIR/$DEST_DIR/$PLUGIN_NAME.zip" # erase any old build
cd ..
zip -r "$DIR/$DEST_DIR/$PLUGIN_NAME.zip" "$PLUGIN_NAME" #zip tmp dir

# erase tmp dir
rm -rf $TMP_DIR

echo "Zip file created in $DIR/$DEST_DIR/$PLUGIN_NAME.zip"
